apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote-app-replica-sets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app-pod
  template:
    metadata:
      labels:
        app: vote-app-pod
    spec:
      containers:
        - name: vote-app
          image: sandyjswl/vote-app:v2.0
          ports:
            - containerPort: 5000