apiVersion: v1
kind: Service
metadata:
    name: redisdb
spec:
    type: ClusterIP
    selector:
        app: redis-pod
    ports:
        - protocol: TCP
          port:  6379
          targetPort: 6379
