apiVersion: v1
kind: Service
metadata:
  name: vote-app-svc
spec:
  type: NodePort
  selector:
    app: vote-app-pod
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30003
