apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: vote-app-rs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vote-app-pod
  template:
    metadata:
      labels:
        app: vote-app-pod
    spec:
      containers:
        - name: vote-app
          image: sandyjswl/vote-app:v3.0
          ports:
            - containerPort: 5000
          env:
            - name: REDIS_HOST
              value: redisdb
            - name: REDIS_PORT
              value: "6379"